version: '3.1'
services:
  guestbook_api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        - PROJECT_PORT=5050
    container_name: guestbook_api
    restart: on-failure
    ports:
        - "5050:5050"
    networks:
        - back
    environment:
        ASPNETCORE_ENVIRONMENT: 'Development'
        ConnectionStrings__DbConnection: 'Server=sql_server;Database=GuestBookDB;Encrypt=True;TrustServerCertificate=True;User ID=SA;Password=MySecretPassword!'

  guestbook_client:
    depends_on:
        - guestbook_api
    build:
        context: ./client
        dockerfile: Dockerfile
    container_name: 'guestbook_client'
    restart: on-failure
    ports:
        - "4200:80"
    networks:
        - back
        - front

  sql_server:
          image: mcr.microsoft.com/mssql/server:2017-latest
          container_name: sql_server
          ports:
              - 1433:1433
          networks:
              - back
          environment:
              SA_PASSWORD: MySecretPassword!
              ACCEPT_EULA: "Y"

networks:
    back:
        driver: bridge
    front:
        driver: bridge