// <auto-generated />
using System;
using GuestBook.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuestBook.DAL.Migrations
{
    [DbContext(typeof(GuestBookContext))]
    partial class GuestBookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuestBook.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Courtney Parisian",
                            Body = "Quia accusantium consequatur.\nSapiente dolorum ducimus ab voluptatem voluptas autem quia.\nIure eius iusto soluta ducimus sapiente.\nRepudiandae quia omnis reiciendis.",
                            CreatedAt = new DateTime(2023, 7, 9, 22, 15, 37, 181, DateTimeKind.Local).AddTicks(8688),
                            PostId = 5
                        },
                        new
                        {
                            Id = 2,
                            Author = "Elsie Hahn",
                            Body = "Ullam ullam et natus quo et rerum molestiae.\nSit quibusdam ratione atque quae autem quia omnis nemo.\nQuibusdam quia omnis rerum maxime libero qui consequuntur sequi.\nBlanditiis vel et eos occaecati exercitationem iste consequatur illo.\nPerspiciatis rerum a",
                            CreatedAt = new DateTime(2023, 7, 10, 7, 37, 30, 524, DateTimeKind.Local).AddTicks(461),
                            PostId = 4
                        },
                        new
                        {
                            Id = 3,
                            Author = "Darrel Wyman",
                            Body = "Et reiciendis eaque.",
                            CreatedAt = new DateTime(2023, 7, 10, 6, 46, 11, 265, DateTimeKind.Local).AddTicks(4219),
                            PostId = 4
                        },
                        new
                        {
                            Id = 4,
                            Author = "Mattie Hackett",
                            Body = "Eveniet sit vel. Sunt magni nostrum et ex. Reprehenderit nihil maxime qui doloribus sequi provident. Possimus pariatur tempore unde magni ipsam cum. Ducimus odit atque omnis sequi aut. Ut officia perspiciatis reprehenderit dolor.",
                            CreatedAt = new DateTime(2023, 7, 10, 17, 55, 22, 51, DateTimeKind.Local).AddTicks(5608),
                            PostId = 1
                        },
                        new
                        {
                            Id = 5,
                            Author = "Maggie Mills",
                            Body = "Quis quaerat nihil sequi mollitia modi. Molestias asperiores voluptate qui nihil. Provident ut laudantium soluta consequatur quo delectus.",
                            CreatedAt = new DateTime(2023, 7, 10, 6, 19, 31, 894, DateTimeKind.Local).AddTicks(4197),
                            PostId = 1
                        },
                        new
                        {
                            Id = 6,
                            Author = "Virgil Wilderman",
                            Body = "Molestiae velit totam aliquam unde odit itaque sequi. Quis saepe fugit dolorem quia. Non voluptas nostrum dolores et omnis illo. Voluptas natus nihil doloribus eos voluptatem et facere omnis.",
                            CreatedAt = new DateTime(2023, 7, 10, 1, 44, 27, 819, DateTimeKind.Local).AddTicks(4838),
                            PostId = 8
                        },
                        new
                        {
                            Id = 7,
                            Author = "Kevin Howell",
                            Body = "Dolorem non libero natus pariatur sed suscipit.",
                            CreatedAt = new DateTime(2023, 7, 10, 9, 7, 35, 9, DateTimeKind.Local).AddTicks(258),
                            PostId = 7
                        },
                        new
                        {
                            Id = 8,
                            Author = "Sonja Gibson",
                            Body = "recusandae",
                            CreatedAt = new DateTime(2023, 7, 10, 0, 36, 50, 690, DateTimeKind.Local).AddTicks(3286),
                            PostId = 5
                        },
                        new
                        {
                            Id = 9,
                            Author = "Kristen Altenwerth",
                            Body = "Asperiores ea aliquam voluptatem et omnis adipisci voluptate at.\nAt consectetur sed cumque ut.\nDeleniti ex natus exercitationem eveniet repellat earum et dolores sint.",
                            CreatedAt = new DateTime(2023, 7, 10, 2, 43, 44, 826, DateTimeKind.Local).AddTicks(5643),
                            PostId = 1
                        },
                        new
                        {
                            Id = 10,
                            Author = "Kendra Tromp",
                            Body = "Fuga sunt non est dolorem. Aliquid enim voluptatem a iusto temporibus sunt velit. Reiciendis expedita totam et asperiores nihil rem quaerat architecto. Labore et blanditiis sit suscipit at dignissimos quis incidunt eveniet.",
                            CreatedAt = new DateTime(2023, 7, 10, 20, 9, 9, 220, DateTimeKind.Local).AddTicks(4859),
                            PostId = 1
                        },
                        new
                        {
                            Id = 11,
                            Author = "Rogelio Parisian",
                            Body = "Quia dolorum qui dignissimos vel.\nSuscipit dolores ipsa.\nVoluptatem non illo.",
                            CreatedAt = new DateTime(2023, 7, 10, 15, 17, 58, 882, DateTimeKind.Local).AddTicks(9012),
                            PostId = 10
                        },
                        new
                        {
                            Id = 12,
                            Author = "Damon Doyle",
                            Body = "Dolor consequuntur dolore.\nQuibusdam nihil rerum quibusdam voluptate enim voluptatem et.\nVoluptate culpa et consequatur saepe est.\nOmnis quas iusto adipisci.",
                            CreatedAt = new DateTime(2023, 7, 10, 10, 45, 50, 489, DateTimeKind.Local).AddTicks(1491),
                            PostId = 4
                        },
                        new
                        {
                            Id = 13,
                            Author = "Milton Grimes",
                            Body = "Placeat veritatis optio culpa reiciendis maxime rerum qui deleniti.\nAutem iusto quam unde harum.",
                            CreatedAt = new DateTime(2023, 7, 9, 20, 54, 46, 926, DateTimeKind.Local).AddTicks(7743),
                            PostId = 7
                        },
                        new
                        {
                            Id = 14,
                            Author = "Reginald Fritsch",
                            Body = "Suscipit temporibus eligendi consequatur nobis delectus expedita.\nDoloremque ut aut voluptatem eos incidunt aut sunt.",
                            CreatedAt = new DateTime(2023, 7, 9, 23, 15, 13, 343, DateTimeKind.Local).AddTicks(6382),
                            PostId = 1
                        },
                        new
                        {
                            Id = 15,
                            Author = "Sabrina Larson",
                            Body = "Cupiditate dicta delectus sunt dolorum dolor dolorum labore. Id inventore modi. Architecto quia qui aut. Eaque est debitis culpa ex asperiores dolorem. Accusamus voluptate soluta dolores facere quis. Repellendus facilis vel excepturi.",
                            CreatedAt = new DateTime(2023, 7, 10, 10, 51, 47, 274, DateTimeKind.Local).AddTicks(4495),
                            PostId = 9
                        },
                        new
                        {
                            Id = 16,
                            Author = "Kristina Jacobi",
                            Body = "Incidunt dolorem commodi est id in eos laboriosam repellat occaecati.",
                            CreatedAt = new DateTime(2023, 7, 10, 15, 10, 15, 328, DateTimeKind.Local).AddTicks(216),
                            PostId = 9
                        },
                        new
                        {
                            Id = 17,
                            Author = "Andres Ratke",
                            Body = "aut",
                            CreatedAt = new DateTime(2023, 7, 10, 12, 1, 53, 671, DateTimeKind.Local).AddTicks(6491),
                            PostId = 3
                        },
                        new
                        {
                            Id = 18,
                            Author = "Bruce Dach",
                            Body = "optio",
                            CreatedAt = new DateTime(2023, 7, 10, 0, 8, 42, 862, DateTimeKind.Local).AddTicks(9250),
                            PostId = 7
                        },
                        new
                        {
                            Id = 19,
                            Author = "Ana Kshlerin",
                            Body = "commodi",
                            CreatedAt = new DateTime(2023, 7, 10, 7, 53, 36, 231, DateTimeKind.Local).AddTicks(6867),
                            PostId = 1
                        },
                        new
                        {
                            Id = 20,
                            Author = "Fernando Reynolds",
                            Body = "Facere a est velit.\nQuis aut et et sed excepturi.",
                            CreatedAt = new DateTime(2023, 7, 10, 15, 41, 46, 291, DateTimeKind.Local).AddTicks(1884),
                            PostId = 9
                        },
                        new
                        {
                            Id = 21,
                            Author = "Ervin Jacobs",
                            Body = "Ut aperiam nihil dolores culpa accusamus eveniet minus.",
                            CreatedAt = new DateTime(2023, 7, 10, 1, 53, 56, 535, DateTimeKind.Local).AddTicks(4187),
                            PostId = 1
                        },
                        new
                        {
                            Id = 22,
                            Author = "Nathaniel Hane",
                            Body = "sit",
                            CreatedAt = new DateTime(2023, 7, 10, 16, 39, 12, 442, DateTimeKind.Local).AddTicks(5779),
                            PostId = 2
                        },
                        new
                        {
                            Id = 23,
                            Author = "Lamar Roob",
                            Body = "Quibusdam ipsum et iusto culpa nesciunt repudiandae unde et explicabo.\nEst sed voluptatum velit veritatis corrupti omnis mollitia eos.\nRepellendus rerum vero corporis sit tempora.",
                            CreatedAt = new DateTime(2023, 7, 9, 23, 38, 16, 65, DateTimeKind.Local).AddTicks(8302),
                            PostId = 4
                        },
                        new
                        {
                            Id = 24,
                            Author = "Phillip Volkman",
                            Body = "Molestiae tempora ullam.",
                            CreatedAt = new DateTime(2023, 7, 10, 11, 37, 3, 977, DateTimeKind.Local).AddTicks(7592),
                            PostId = 9
                        },
                        new
                        {
                            Id = 25,
                            Author = "Saul Kreiger",
                            Body = "Nam qui ut aut omnis commodi.",
                            CreatedAt = new DateTime(2023, 7, 10, 1, 19, 34, 740, DateTimeKind.Local).AddTicks(4209),
                            PostId = 9
                        },
                        new
                        {
                            Id = 26,
                            Author = "Patricia Weimann",
                            Body = "Quae sequi quis ut.",
                            CreatedAt = new DateTime(2023, 7, 10, 12, 25, 55, 667, DateTimeKind.Local).AddTicks(7230),
                            PostId = 6
                        },
                        new
                        {
                            Id = 27,
                            Author = "Lonnie Hermann",
                            Body = "esse",
                            CreatedAt = new DateTime(2023, 7, 9, 23, 29, 15, 209, DateTimeKind.Local).AddTicks(8619),
                            PostId = 9
                        },
                        new
                        {
                            Id = 28,
                            Author = "Christy Nader",
                            Body = "Et ab quis possimus et velit cumque aut id.\nLaudantium ipsa vel impedit voluptates facere non accusantium.\nVoluptas non aut voluptas et porro rem.\nQuibusdam sit at ut omnis veritatis sunt temporibus.",
                            CreatedAt = new DateTime(2023, 7, 10, 14, 6, 57, 840, DateTimeKind.Local).AddTicks(360),
                            PostId = 8
                        },
                        new
                        {
                            Id = 29,
                            Author = "Lance Schiller",
                            Body = "molestiae",
                            CreatedAt = new DateTime(2023, 7, 10, 13, 34, 39, 951, DateTimeKind.Local).AddTicks(7997),
                            PostId = 8
                        },
                        new
                        {
                            Id = 30,
                            Author = "Ernestine Erdman",
                            Body = "Nihil odio fugit doloremque illum modi.",
                            CreatedAt = new DateTime(2023, 7, 10, 14, 30, 19, 310, DateTimeKind.Local).AddTicks(7281),
                            PostId = 6
                        });
                });

            modelBuilder.Entity("GuestBook.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Marilyn Orn",
                            Body = "Et consequatur non facilis omnis id quae corporis suscipit rerum. Rerum minus qui officia ipsam et. Minima aut eum dolorem magni a cumque non. Animi perspiciatis praesentium. Voluptatum sunt aperiam qui distinctio voluptatem est aspernatur laborum. Delectus commodi omnis accusantium voluptatem sit quo.",
                            CreatedAt = new DateTime(2023, 7, 10, 16, 45, 9, 817, DateTimeKind.Local).AddTicks(9279)
                        },
                        new
                        {
                            Id = 2,
                            Author = "Maggie Hoeger",
                            Body = "Itaque sunt commodi dolores libero porro ut molestias ea ratione.\nId nisi expedita ipsam quam sint adipisci dolore ut et.\nDelectus et recusandae animi.",
                            CreatedAt = new DateTime(2023, 7, 10, 1, 7, 34, 923, DateTimeKind.Local).AddTicks(3873)
                        },
                        new
                        {
                            Id = 3,
                            Author = "Olga Beer",
                            Body = "Soluta et doloribus ducimus facere aut fugiat quisquam officia.",
                            CreatedAt = new DateTime(2023, 7, 9, 21, 28, 47, 818, DateTimeKind.Local).AddTicks(8648)
                        },
                        new
                        {
                            Id = 4,
                            Author = "Rafael Morar",
                            Body = "Blanditiis ea corporis laboriosam minima omnis qui.\nNumquam sed veniam et consequatur consequatur.",
                            CreatedAt = new DateTime(2023, 7, 9, 23, 9, 15, 479, DateTimeKind.Local).AddTicks(7569)
                        },
                        new
                        {
                            Id = 5,
                            Author = "Vivian Ziemann",
                            Body = "Distinctio autem quis.\nNecessitatibus voluptatum ipsum perferendis aperiam architecto eos sit.",
                            CreatedAt = new DateTime(2023, 7, 10, 16, 7, 49, 194, DateTimeKind.Local).AddTicks(7883)
                        },
                        new
                        {
                            Id = 6,
                            Author = "Larry Runte",
                            Body = "Aliquam exercitationem corporis harum dolores in rerum veritatis repellendus.\nItaque reiciendis quis nemo aspernatur rerum illo in.\nRerum voluptas quos.\nMaiores consequatur molestiae consectetur sit sit et soluta.",
                            CreatedAt = new DateTime(2023, 7, 10, 13, 15, 37, 652, DateTimeKind.Local).AddTicks(2069)
                        },
                        new
                        {
                            Id = 7,
                            Author = "Mathew Aufderhar",
                            Body = "Consequatur culpa sint qui laudantium perspiciatis numquam ducimus et.\nOmnis sed et ut nisi sapiente fuga consequuntur.\nLaudantium quaerat a consequuntur.\nDoloremque ut voluptatum quia quod est quos a hic.\nId eveniet officia et.",
                            CreatedAt = new DateTime(2023, 7, 10, 19, 38, 1, 403, DateTimeKind.Local).AddTicks(8769)
                        },
                        new
                        {
                            Id = 8,
                            Author = "Mathew Fritsch",
                            Body = "Sequi distinctio et excepturi ut.",
                            CreatedAt = new DateTime(2023, 7, 10, 14, 47, 30, 579, DateTimeKind.Local).AddTicks(4338)
                        },
                        new
                        {
                            Id = 9,
                            Author = "Dale Huel",
                            Body = "Numquam nulla ex perferendis qui tenetur non beatae voluptate.\nVeniam id molestias et velit pariatur placeat aspernatur.\nSimilique sed repellat accusamus eos.\nEum soluta porro labore iste ducimus velit molestiae beatae.\nDoloremque atque porro enim tempore quo ipsa rerum.",
                            CreatedAt = new DateTime(2023, 7, 9, 23, 2, 19, 438, DateTimeKind.Local).AddTicks(1146)
                        },
                        new
                        {
                            Id = 10,
                            Author = "Gary Stark",
                            Body = "Aspernatur doloribus tenetur autem illum et incidunt excepturi sint.",
                            CreatedAt = new DateTime(2023, 7, 10, 10, 56, 32, 347, DateTimeKind.Local).AddTicks(4735)
                        });
                });

            modelBuilder.Entity("GuestBook.DAL.Entities.Comment", b =>
                {
                    b.HasOne("GuestBook.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("GuestBook.DAL.Entities.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
